/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg2048;

import TuplePair.TuplePair;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Octavi
 */
public class VistaRanking extends javax.swing.JFrame {

    private CPJugarPartida CPJugar;

    /**
     * Creates new form VistaRanking
     */
    public VistaRanking() {
        initComponents();
        CPJugar = null;
    }

    VistaRanking(String user, CPJugarPartida cpj) {
        initComponents();
        CPJugar = cpj;
        txtJugador.setText(user);
        escriureRank(user);
    }
    
     void setCPJugar(CPJugarPartida cp) {
        CPJugar = cp;
    }
    private void escriureRank(String user){
        try {
            ArrayList<TuplePair<String,Integer>> rank = CPJugar.consultarRanking();
            Vector<String> jugadors = new Vector<>();
            Vector<String> puntuacions = new Vector<>();
            for (TuplePair<String,Integer> tuple : rank) {
                jugadors.add(tuple.getL());
                puntuacions.add(""+tuple.getR());
                if(tuple.getL().equals(user)) txtPuntuacio.setText(""+tuple.getR());
            }
            listJugador.setListData(jugadors);
            listPuntuacio.setListData(puntuacions);
            
        } catch (Exception ex) {
            lblError.setText(ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJugador = new javax.swing.JLabel();
        lblPuntuacio = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listJugador = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        listPuntuacio = new javax.swing.JList();
        btnJugar = new javax.swing.JButton();
        btnSortir = new javax.swing.JButton();
        txtJugador = new javax.swing.JTextField();
        txtPuntuacio = new javax.swing.JTextField();
        lblError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ranking");

        lblJugador.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblJugador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJugador.setText("Jugador");

        lblPuntuacio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPuntuacio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPuntuacio.setText("Puntuació");

        jScrollPane1.setViewportView(listJugador);

        jScrollPane2.setViewportView(listPuntuacio);

        btnJugar.setText("Jugar");
        btnJugar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnJugarMousePressed(evt);
            }
        });

        btnSortir.setText("Sortir");
        btnSortir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSortirMousePressed(evt);
            }
        });

        txtJugador.setToolTipText("");
        txtJugador.setFocusable(false);

        txtPuntuacio.setFocusable(false);

        lblError.setForeground(new java.awt.Color(255, 51, 51));
        lblError.setFocusable(false);
        lblError.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPuntuacio))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSortir, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPuntuacio, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(lblError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJugador)
                    .addComponent(lblPuntuacio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPuntuacio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnJugar)
                    .addComponent(btnSortir))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnJugarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJugarMousePressed
        CPJugar.inicializarPartida();
    }//GEN-LAST:event_btnJugarMousePressed

    private void btnSortirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSortirMousePressed
        System.exit(WIDTH);
    }//GEN-LAST:event_btnSortirMousePressed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJugar;
    private javax.swing.JButton btnSortir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblJugador;
    private javax.swing.JLabel lblPuntuacio;
    private javax.swing.JList listJugador;
    private javax.swing.JList listPuntuacio;
    private javax.swing.JTextField txtJugador;
    private javax.swing.JTextField txtPuntuacio;
    // End of variables declaration//GEN-END:variables

   
}
