/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg2048;

import java.awt.event.KeyEvent;
import java.time.Clock;
import java.util.Set;
import java.util.Vector;
import javax.swing.JLabel;
import org.javatuples.Quartet;
import org.javatuples.Triplet;

/**
 *
 * @author Octavi
 */
public class VistaJugarPartida extends javax.swing.JFrame {

    private Vector<JLabel> matriu;
    private CPJugarPartida CPJugar;
    private String moviment;
    /**
     * Creates new form VistaJugarPartida
     */
    VistaJugarPartida() {
        initComponents();
        llegirMatriu();
        moviment = "";
    }
    
    void setPuntuacio(Integer value0) {
        lblPuntuacio.setText(""+value0);
    }
    
    void initPartida(Triplet<Integer, Integer, Set<Triplet<Integer, Integer, Integer>>> infoStart) {
        //puntInicial, millorPunt, caselles(i,j,num)
        lblPuntuacio.setText(""+infoStart.getValue0());
        lblMillorPuntuacio.setText(""+infoStart.getValue1());
        actualitzarCaselles(infoStart.getValue2());
    }

    
    public void setCPJugar(CPJugarPartida cpjugar){
        CPJugar = cpjugar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl00 = new javax.swing.JLabel();
        lbl10 = new javax.swing.JLabel();
        lbl20 = new javax.swing.JLabel();
        lbl30 = new javax.swing.JLabel();
        lbl01 = new javax.swing.JLabel();
        lbl11 = new javax.swing.JLabel();
        lbl21 = new javax.swing.JLabel();
        lbl31 = new javax.swing.JLabel();
        lbl02 = new javax.swing.JLabel();
        lbl12 = new javax.swing.JLabel();
        lbl22 = new javax.swing.JLabel();
        lbl32 = new javax.swing.JLabel();
        lbl03 = new javax.swing.JLabel();
        lbl13 = new javax.swing.JLabel();
        lbl23 = new javax.swing.JLabel();
        lbl33 = new javax.swing.JLabel();
        lblPuntuacio = new javax.swing.JLabel();
        lblMillorPuntuacio = new javax.swing.JLabel();
        txtPuntuacio = new javax.swing.JTextField();
        txtMillorPuntuacio = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("2048");
        setIconImages(null);
        setMaximumSize(new java.awt.Dimension(338, 368));
        setMinimumSize(new java.awt.Dimension(338, 368));
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        lbl00.setFont(new java.awt.Font("Arial", 1, 60)); // NOI18N
        lbl00.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl00.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbl10.setFont(new java.awt.Font("Arial", 1, 60)); // NOI18N
        lbl10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbl20.setFont(lbl00.getFont());
        lbl20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl20.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbl30.setFont(lbl00.getFont());
        lbl30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl30.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbl01.setFont(new java.awt.Font("Arial", 1, 60)); // NOI18N
        lbl01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl01.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbl11.setFont(new java.awt.Font("Arial", 1, 60)); // NOI18N
        lbl11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl11.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbl21.setFont(lbl00.getFont());
        lbl21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl21.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbl31.setFont(lbl00.getFont());
        lbl31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl31.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbl02.setFont(new java.awt.Font("Arial", 1, 60)); // NOI18N
        lbl02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl02.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbl12.setFont(new java.awt.Font("Arial", 1, 60)); // NOI18N
        lbl12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl12.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbl22.setFont(lbl00.getFont());
        lbl22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl22.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbl32.setFont(lbl00.getFont());
        lbl32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl32.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbl03.setFont(new java.awt.Font("Arial", 1, 60)); // NOI18N
        lbl03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl03.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbl13.setFont(lbl00.getFont());
        lbl13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl13.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbl23.setFont(lbl00.getFont());
        lbl23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl23.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbl33.setFont(lbl00.getFont());
        lbl33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl33.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblPuntuacio.setText("Puntuació:");

        lblMillorPuntuacio.setText("Millor Puntuació:");

        txtPuntuacio.setEditable(false);
        txtPuntuacio.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPuntuacio.setText("0");
        txtPuntuacio.setFocusable(false);

        txtMillorPuntuacio.setEditable(false);
        txtMillorPuntuacio.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtMillorPuntuacio.setText("0");
        txtMillorPuntuacio.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl30, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lbl31, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lbl32, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lbl33, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPuntuacio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPuntuacio, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMillorPuntuacio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMillorPuntuacio, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl00, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl01, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl02, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl03, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl10, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lbl11, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lbl12, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lbl13, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl20, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lbl21, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lbl22, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lbl23, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPuntuacio, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPuntuacio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMillorPuntuacio, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMillorPuntuacio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl00, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl02, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl03, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl01, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl10, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl11, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl12, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl13, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl20, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl21, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl22, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl23, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl30, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl31, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl32, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl33, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        int down = KeyEvent.VK_DOWN;//40
        int up = KeyEvent.VK_UP;//38
        int left = KeyEvent.VK_LEFT;//37
        int right = KeyEvent.VK_RIGHT;//39
        
        if(evt.getKeyCode()==40) moviment = "avall";
        else if (evt.getKeyCode()==38) moviment = "amunt";
        else if (evt.getKeyCode()==37) moviment = "esquerra";
        else if (evt.getKeyCode()==39) moviment = "dreta";
        else {
            moviment += evt.getKeyChar();
            System.out.println(moviment);
            if(moviment.equals("fi")) CPJugar.inicializarFinal(false,txtPuntuacio.getText());
            return;
        }
        
        Quartet<Boolean,Boolean,Integer,Set<Triplet<Integer,Integer,Integer>>> info = CPJugar.ferMoviment(moviment);
        //guanyada, acabada, puntuacio, set(i, j, num)
        
        moviment = "";
        txtPuntuacio.setText(""+info.getValue2());
        buidarCaselles();
        actualitzarCaselles(info.getValue3());
        if(info.getValue1())CPJugar.inicializarFinal(info.getValue0(), ""+info.getValue2());

    }//GEN-LAST:event_formKeyPressed


    private void buidarCaselles() {
    	for (JLabel jLabel : matriu) {
			jLabel.setText("");
		}
	}


	// Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl00;
    private javax.swing.JLabel lbl01;
    private javax.swing.JLabel lbl02;
    private javax.swing.JLabel lbl03;
    private javax.swing.JLabel lbl10;
    private javax.swing.JLabel lbl11;
    private javax.swing.JLabel lbl12;
    private javax.swing.JLabel lbl13;
    private javax.swing.JLabel lbl20;
    private javax.swing.JLabel lbl21;
    private javax.swing.JLabel lbl22;
    private javax.swing.JLabel lbl23;
    private javax.swing.JLabel lbl30;
    private javax.swing.JLabel lbl31;
    private javax.swing.JLabel lbl32;
    private javax.swing.JLabel lbl33;
    private javax.swing.JLabel lblMillorPuntuacio;
    private javax.swing.JLabel lblPuntuacio;
    private javax.swing.JTextField txtMillorPuntuacio;
    private javax.swing.JTextField txtPuntuacio;
    // End of variables declaration//GEN-END:variables

    private void llegirMatriu() {
        matriu = new Vector<JLabel>();
        matriu.add(lbl00);
        matriu.add(lbl01);
        matriu.add(lbl02);
        matriu.add(lbl03);
        matriu.add(lbl10);
        matriu.add(lbl11);
        matriu.add(lbl12);
        matriu.add(lbl13);
        matriu.add(lbl20);
        matriu.add(lbl21);
        matriu.add(lbl22);
        matriu.add(lbl23);
        matriu.add(lbl30);
        matriu.add(lbl31);
        matriu.add(lbl32);
        matriu.add(lbl33);
    }

    private void actualitzarCaselles(Set<Triplet<Integer, Integer, Integer>> caselles) {
        int i;
        int j;
        int num;
        System.out.println(caselles.size());
        for (Triplet<Integer, Integer, Integer> c : caselles) {
            i = c.getValue0();
            j = c.getValue1();
            num = c.getValue2();
            matriu.get(i*4+j).setText(""+num);
        }
    }

   
}
